from fluxify.transformers import validate_transformation_args


def ubiflow_equipments(transformation: dict):
    validate_transformation_args(transformation)

    equipment_list = {
        'accoudoir_central': {'name': 'possède un accoudoir central', 'group': 'Equipements Confort'},
        'affichage_tete_haute': {'name': 'affichage tête haute', 'group': 'Equipements Confort'},
        'allumage_automatique_des_feux': {'name': 'allumage automatique des feux', 'group': 'Equipements Confort'},
        'auto_radio': {'name': 'auto-radio', 'group': 'Equipements Confort'},
        'auto_radio_commande_au_volant': {'name': 'auto-radio commandé au volant', 'group': 'Equipements Confort'},
        'auvent': {'name': 'auvent', 'group': 'Equipements Confort'},
        'banquette_1_3_2_3': {'name': 'banquette 1/3 - 2/3', 'group': 'Equipements Confort'},
        'barres_de_toit': {'name': 'barres de toit', 'group': 'Equipements Confort'},
        'bulle_electrique': {'name': 'bulle électrique', 'group': 'Equipements Confort'},
        'bulle_haute': {'name': 'bulle haute', 'group': 'Equipements Confort'},
        'bulle_reglable': {'name': 'bulle réglable', 'group': 'Equipements Confort'},
        'capote_electrique': {'name': 'capote électrique', 'group': 'Equipements Confort'},
        'carte_main_libre': {'name': 'carte main libre', 'group': 'Equipements Confort'},
        'chauffage_stationnaire': {'name': 'chauffage stationnaire', 'group': 'Equipements Confort'},
        'climatisation': {'name': 'climatisation', 'group': 'Equipements Confort'},
        'demarreur_electrique': {'name': 'démarreur électrique', 'group': 'Equipements Confort'},
        'detecteur_de_pluie': {'name': 'détecteur de pluie', 'group': 'Equipements Confort'},
        'direction_assistee': {'name': 'direction assistée', 'group': 'Equipements Confort'},
        'dosseret': {'name': 'dosseret', 'group': 'Equipements Confort'},
        'fermeture_centralisee': {'name': 'fermeture centralisée', 'group': 'Equipements Confort'},
        'filet_anti_remous': {'name': 'filet anti remous', 'group': 'Equipements Confort'},
        'gps': {'name': 'Système de navigation', 'group': 'Equipements Confort'},
        'gps_16_9eme': {'name': 'GPS 16/9ème', 'group': 'Equipements Confort'},
        'gps_couleur': {'name': 'GPS couleur', 'group': 'Equipements Confort'},
        'gps_tactile': {'name': 'GPS tactile', 'group': 'Equipements Confort'},
        'gps_tv': {'name': 'GPS TV', 'group': 'Equipements Confort'},
        'hard_top': {'name': 'hard top', 'group': 'Equipements Confort'},
        'housse_de_protection': {'name': 'housse de protection', 'group': 'Equipements Confort'},
        'interieur_bois': {'name': 'intérieur bois', 'group': 'Equipements Confort'},
        'jupe': {'name': 'jupe', 'group': 'Equipements Confort'},
        'lecteur_dvd': {'name': 'lecteur DVD', 'group': 'Equipements Confort'},
        'manchons': {'name': 'manchons', 'group': 'Equipements Confort'},
        'marchepieds': {'name': 'marchepieds', 'group': 'Equipements Confort'},
        'ordinateur_de_bord': {'name': 'ordinateur de bord', 'group': 'Equipements Confort'},
        'poignees_chauffantes': {'name': 'poignées chauffantes', 'group': 'Equipements Confort'},
        'porte_bagage': {'name': 'porte bagage', 'group': 'Equipements Confort'},
        'porte_laterale': {'name': 'porte latérale', 'group': 'Equipements Confort'},
        'radio': {'name': 'radio', 'group': 'Equipements Confort'},
        'repose_pieds': {'name': 'repose pieds', 'group': 'Equipements Confort'},
        'retroviseurs_degivrants': {'name': 'rétroviseurs dégivrants', 'group': 'Equipements Confort'},
        'retroviseurs_electriques': {'name': 'rétroviseurs électriques', 'group': 'Equipements Confort'},
        'retroviseurs_rabattables': {'name': 'rétroviseurs rabattables', 'group': 'Equipements Confort'},
        'rideaux_pare_soleil': {'name': 'rideaux pare-soleil', 'group': 'Equipements Confort'},
        'sacoches': {'name': 'sacoches', 'group': 'Equipements Confort'},
        'selle_confort': {'name': 'selle confort', 'group': 'Equipements Confort'},
        'selle_reglable': {'name': 'selle réglable', 'group': 'Equipements Confort'},
        'sieges_chauffants': {'name': 'sièges chauffants', 'group': 'Equipements Confort'},
        'sieges_electriques': {'name': 'sièges électriques', 'group': 'Equipements Confort'},
        'sieges_enfants_integres': {'name': 'sièges enfants intégrés', 'group': 'Equipements Confort'},
        'sieges_pivotants': {'name': 'sièges pivotants', 'group': 'Equipements Confort'},
        'sieges_sport': {'name': 'sièges sport', 'group': 'Equipements Confort'},
        'sissy_bar': {'name': 'sissy bar', 'group': 'Equipements Confort'},
        'systeme_d_aide_au_stationnement': {'name': "présence d'un système d'aide au stationnement",
                                            'group': 'Equipements Confort'},
        'telephone_fixe': {'name': 'téléphone fixe', 'group': 'Equipements Confort'},
        'predisposition_telephone': {'name': 'prédisposition téléphone', 'group': 'Equipements Confort'},
        'toit_ouvrant': {'name': 'toit ouvrant', 'group': 'Equipements Confort'},
        'toit_ouvrant_electrique': {'name': 'toit ouvrant électrique', 'group': 'Equipements Confort'},
        'toit_ouvrant_electrique_en_verre': {'name': 'toit ouvrant électrique en verre',
                                             'group': 'Equipements Confort'},
        'toit_ouvrant_panoramique': {'name': 'toit ouvrant panoramique', 'group': 'Equipements Confort'},
        'toit_panoramique': {'name': 'toit panoramique', 'group': 'Equipements Confort'},
        'top_case': {'name': 'top case', 'group': 'Equipements Confort'},
        'top_case_avant': {'name': 'top case avant', 'group': 'Equipements Confort'},
        'valises': {'name': 'valises', 'group': 'Equipements Confort'},
        'vitres_electriques': {'name': 'vitres électriques', 'group': 'Equipements Confort'},
        'vitres_surteintees': {'name': 'vitres surteintées', 'group': 'Equipements Confort'},
        'volant_bois': {'name': 'volant bois', 'group': 'Equipements Confort'},
        'volant_multifonctions': {'name': 'volant multifonctions', 'group': 'Equipements Confort'},
        'volant_reglable': {'name': 'volant réglable', 'group': 'Equipements Confort'},
        'volant_sport': {'name': 'volant sport', 'group': 'Equipements Confort'},
        'sieges_electriques_a_memoire': {'name': 'siège(s) réglable(s) électriquement avec mémorisation des réglages',
                                         'group': 'Equipements Confort'},
        'commandes_reculees': {'name': 'commandes reculées', 'group': 'Equipements Confort'},
        'guidon_reglable': {'name': 'guidon réglable', 'group': 'Equipements Confort'},
        'kit_passager': {'name': 'kit passager (assise, repose pieds...)', 'group': 'Equipements Confort'},
        'pare_mains': {'name': 'pare-mains', 'group': 'Equipements Confort'},
        'repose_pieds_reglable': {'name': 'repose-pieds réglable', 'group': 'Equipements Confort'},
        'selle_basse': {'name': 'selle basse', 'group': 'Equipements Confort'},
        'selle_haute': {'name': 'selle haute', 'group': 'Equipements Confort'},
        'selle_chauffante': {'name': 'selle chauffante', 'group': 'Equipements Confort'},
        'selle_personnalisee': {'name': 'selle personnalisée', 'group': 'Equipements Confort'},
        'bluetooth': {'name': 'technologie de réseau local sans fil', 'group': 'Equipements Confort'},
        'tete_de_fourche': {'name': 'tête de fourche', 'group': 'Equipements Confort'},
        'dosseret_type': {'name': 'type de dosseret', 'group': 'Equipements Confort'},
        'sieges_reglables_en_hauteur': {'name': 'sieges reglables en hauteur', 'group': 'Equipements Confort'},
        'accumulateur_de_chaleur_latente': {'name': 'Accumulateur de chaleur latente', 'group': 'Equipements Confort'},
        'aide_au_demarrage_en_pente': {'name': 'Aide au demarrage en pente', 'group': 'Equipements Confort'},
        'vitres_avant_electriques': {'name': 'vitres avant éléctriques', 'group': 'Equipements Confort'},
        'volant_reglages': {'name': 'réglages disponibles pour le volant', 'group': 'Equipements Confort'},
        'accoudoir_central_arriere': {'name': "dispose d'un accoudoir central arrière", 'group': 'Equipements Confort'},
        'appuie_reins_conduteur': {'name': 'appuie-reins conducteur', 'group': 'Equipements Confort'},
        'appuie_reins_conduteur_electrique': {'name': 'appuie-reins conducteur électrique',
                                              'group': 'Equipements Confort'},
        'appuie_reins_passager': {'name': 'appuie-reins passager', 'group': 'Equipements Confort'},
        'appuie_reins_passager_electrique': {'name': 'appuie-reins passager électrique',
                                             'group': 'Equipements Confort'},
        'suspension_pilotee': {'name': 'suspension pilotée', 'group': 'Equipements Confort'},
        'proteges_mains': {'name': 'proteges mains', 'group': 'Equipements Confort'},
        'nb_reglages_siege_cond': {'name': 'Nombre de réglages du siège conducteur', 'group': 'Equipements Confort'},
        'nb_reglages_siege_pas': {'name': 'Nombre de réglages du siège passager', 'group': 'Equipements Confort'},
        'miroir_courtoisie_conducteur': {'name': 'Miroir de courtoisie coté conducteur',
                                         'group': 'Equipements Confort'},
        'porte_gobelet_avant': {'name': 'Porte gobelet avant', 'group': 'Equipements Confort'},
        'porte_gobelet_arriere': {'name': 'Porte gobelet arrière', 'group': 'Equipements Confort'},
        'lecteur_dvd_avant': {'name': "Lecteur DVD à l'avant", 'group': 'Equipements Confort'},
        'lecteur_dvd_arriere': {'name': "Lecteur DVD à l'arrière", 'group': 'Equipements Confort'},
        'siege_cond_reglable_en_hauteur': {'name': 'siège conducteur réglable', 'group': 'Equipements Confort'},
        'siege_pass_reglable_en_hauteur': {'name': 'siège passager réglable', 'group': 'Equipements Confort'},
        'vitres_arrieres_electriques': {'name': 'Vitres arrières électriques', 'group': 'Equipements Confort'},
        'miroir_courtoisie_passager': {'name': 'Miroir de courtoisie coté Passager', 'group': 'Equipements Confort'},
        'nb_haut_parleurs': {'name': 'Nombre de haut parleurs', 'group': 'Equipements Confort'},
        'ecran_multifonction': {'name': 'Écran multifonction', 'group': 'Equipements Confort'},
        'prise_audio_usb': {'name': 'Prise audio auxilliaire : usb', 'group': 'Equipements Confort'},
        'telephone_commande_au_volant': {'name': "Commande de contrôle d'un téléphone depuis le volant",
                                         'group': 'Equipements Confort'},
        'siege_chauffant_cond': {'name': 'Siege chauffant coté conducteur', 'group': 'Equipements Confort'},
        'siege_chauffant_pass': {'name': 'Siege chauffant coté passager', 'group': 'Equipements Confort'},
        'siege_cond_reglage_lombaire': {
            'name': 'Informations sur le réglages du soutien des lombaires sur le siège conducteur',
            'group': 'Equipements Confort'}, 'siege_pass_reglage_lombaire': {
            'name': 'Informations sur le réglages du soutien des lombaires sur le siège passager',
            'group': 'Equipements Confort'}, 'auto_radio_rds': {
            'name': 'le "Radio Data System" correspond à des données numériques transmises au travers des fréquences FM.',
            'group': 'Equipements Confort'}, 'abs': {
            'name': 'Système antiblocage des freins : évite le blocage des roues pendant le freinage afin de garder le contrôle directionnel du véhicule',
            'group': 'Equipements sécurité'},
        'airbags_frontaux': {'name': "Présence d'airbags frontaux", 'group': 'Equipements sécurité'},
        'airbags_lateraux': {'name': 'airbags latéraux', 'group': 'Equipements sécurité'},
        'alarme': {'name': 'alarme', 'group': 'Equipements sécurité'},
        'afil': {'name': 'Alerte de Franchissement Involontaire de Ligne', 'group': 'Equipements sécurité'},
        'anti_demarrage': {'name': 'anti démarrage', 'group': 'Equipements sécurité'},
        'anti_patinage': {'name': 'anti-patinage', 'group': 'Equipements sécurité'},
        'casque': {'name': 'casque', 'group': 'Equipements sécurité'},
        'clignotants': {'name': 'clignotants', 'group': 'Equipements sécurité'},
        'controle_pression_des_pneus': {'name': 'contrôle pression des pneus', 'group': 'Equipements sécurité'},
        'coupe_circuit': {'name': 'coupe circuit', 'group': 'Equipements sécurité'},
        'esp': {'name': 'Contrôle de stabilité ou Contrôle dynamique de trajectoire', 'group': 'Equipements sécurité'},
        'frein_parking_automatique': {'name': 'frein parking automatique', 'group': 'Equipements sécurité'},
        'freinage_couple': {'name': 'freinage couplé', 'group': 'Equipements sécurité'},
        'freins_arriere_disque': {'name': 'freins arrière disque', 'group': 'Equipements sécurité'},
        'freins_avant_disque': {'name': 'freins avant disque', 'group': 'Equipements sécurité'},
        'homologue_route': {'name': 'homologué route', 'group': 'Equipements sécurité'},
        'phares': {'name': 'phares', 'group': 'Equipements sécurité'},
        'phares_antibrouillard': {'name': 'phares antibrouillard', 'group': 'Equipements sécurité'},
        'pneus_neige': {'name': 'pneus neige', 'group': 'Equipements sécurité'},
        'projecteurs_xenon': {'name': 'projecteurs xénon', 'group': 'Equipements sécurité'},
        'protege_carter': {'name': 'protège carter', 'group': 'Equipements sécurité'},
        'protege_cylindres': {'name': 'protège cylindres', 'group': 'Equipements sécurité'},
        'stabilisateurs': {'name': 'stabilisateurs', 'group': 'Equipements sécurité'},
        'suspension_pneumatique': {'name': 'suspension pneumatique', 'group': 'Equipements sécurité'},
        'suspension_sport': {'name': 'suspension sport', 'group': 'Equipements sécurité'},
        'systeme_d_identification_du_conducteur': {'name': "système d'identification du conducteur",
                                                   'group': 'Equipements sécurité'},
        'tatouage_antivol': {'name': 'tatouage antivol', 'group': 'Equipements sécurité'},
        'warning': {'name': 'warning', 'group': 'Equipements sécurité'},
        'radar_aide_stationnement': {'name': "radar d'aide au stationnement", 'group': 'Equipements sécurité'},
        'radar_obstacle_avant': {'name': "capteur(s) de proximité d'obstacle à l'avant du véhicule",
                                 'group': 'Equipements sécurité'},
        'radar_obstacle_arriere': {'name': "capteur(s) de proximité d'obstacle à l'arrière du véhicule",
                                   'group': 'Equipements sécurité'},
        'feux_detresse': {'name': 'feux de détresse', 'group': 'Equipements sécurité'},
        'airbag': {'name': 'airbag', 'group': 'Equipements sécurité'},
        'camera_recul': {'name': "caméra à l'arrière du véhicule", 'group': 'Equipements sécurité'}, 'asr': {
            'name': "système antipatinage régulant l'accélération pour limiter la perte d'adhérence des roues motrices",
            'group': 'Equipements sécurité'},
        'protections_laterales': {'name': 'protections latérales', 'group': 'Equipements sécurité'},
        'afu': {'name': "Système d'aide au freinage d'urgence", 'group': 'Equipements sécurité'},
        'repartiteur_electronique_de_freinage': {'name': 'répartiteur électronique de freinage',
                                                 'group': 'Equipements sécurité'},
        'fixations_isofix': {'name': 'fixations ISOFIX', 'group': 'Equipements sécurité'},
        'airbags_rideaux': {'name': 'Airbags rideaux', 'group': 'Equipements sécurité'},
        'airbag_anti_sous_marinage': {'name': 'Airbag anti sous-marinage', 'group': 'Equipements sécurité'},
        'verrouillage_automatique_des_portes_en_roulant': {'name': 'verrouillage automatique des portes en roulant',
                                                           'group': 'Equipements sécurité'},
        'blocage_electronique_du_differentiel': {'name': 'blocage électronique du différentiel',
                                                 'group': 'Equipements sécurité'},
        'retroviseur_interieur_electrochrome': {'name': 'rétroviseur interieur electrochrome',
                                                'group': 'Equipements sécurité'},
        'kit_depannage_pneumatique': {'name': 'kit de dépannage pneumatique', 'group': 'Equipements sécurité'},
        'roue_secours': {'name': 'roue de secours', 'group': 'Equipements sécurité'},
        'airbag_conducteur': {'name': "présence d'un airbag conducteur", 'group': 'Equipements sécurité'},
        'phares_directionnels': {
            'name': 'Les phares directionnels tournent avec le changement de direction du véhicule. De ce fait, dans les virages, ils éclairent la route que veut suivre le conducteur, et pas le fossé.',
            'group': 'Equipements sécurité'}, 'feux_de_circulation_diurne': {
            'name': "Dispositif d'éclairage de lumière blanche à l'avant d'un véhicule qui s'allume automatiquement lorsque le véhicule se déplace vers l'avant afin d'accroître la visibilité du véhicule dans des conditions de lumière du jour.",
            'group': 'Equipements sécurité'},
        'type_feux_de_circulation_diurne': {'name': 'type feux de circulation diurne (led, xenon, halogène...)',
                                            'group': 'Equipements sécurité'},
        'antivol_u': {'name': "dispose d'un antivol en U", 'group': 'Equipements sécurité'},
        'antivol_bloc_disque': {'name': "dispose d'un antivol bloc disque", 'group': 'Equipements sécurité'},
        'antivol_chaine': {'name': 'chaine antivol', 'group': 'Equipements sécurité'},
        'airbag_genoux_conducteur': {'name': 'Airbag de protection des genoux coté conducteur',
                                     'group': 'Equipements sécurité'},
        'airbags_rideaux_avant': {'name': 'Airbag de protection latéral tête / vitre', 'group': 'Equipements sécurité'},
        'airbags_rideaux_arriere': {'name': 'Airbag de protection latéral tête / vitre',
                                    'group': 'Equipements sécurité'},
        'airbag_genoux_passager': {'name': 'Airbag de protection des genoux coté Passager',
                                   'group': 'Equipements sécurité'},
        'airbags_lateraux_avants': {'name': 'airbags latéraux avants', 'group': 'Equipements sécurité'},
        'airbags_lateraux_arrieres': {'name': 'airbags latéraux arrières', 'group': 'Equipements sécurité'},
        'airbags_frontaux_avants': {'name': "Présence d'airbags frontaux Avants", 'group': 'Equipements sécurité'},
        'airbags_frontaux_arrieres': {'name': "Présence d'airbags frontaux arrières", 'group': 'Equipements sécurité'},
        'controle_descente': {'name': 'Système de contrôle de la vitesse de descente', 'group': 'Equipements sécurité'},
        'airbag_passager': {'name': 'Airbag coté passager', 'group': 'Equipements sécurité'},
        'airbag_passager_desactivable': {'name': 'Airbag coté passager désactivable', 'group': 'Equipements sécurité'},
        'attelage': {'name': 'attelage', 'group': 'Equipements divers'},
        'carenage': {'name': 'carénage', 'group': 'Equipements divers'},
        'chassis_sport': {'name': 'châssis sport', 'group': 'Equipements divers'},
        'clignotant_goutte_d_eau': {'name': "clignotant goutte d'eau", 'group': 'Equipements divers'},
        'demarreur_manuel': {'name': 'démarreur manuel', 'group': 'Equipements divers'},
        'galerie': {'name': 'galerie', 'group': 'Equipements divers'},
        'garde_boue_arriere': {'name': 'garde boue arrière', 'group': 'Equipements divers'},
        'jantes': {'name': 'materiau des jantes', 'group': 'Equipements divers'},
        'dimension_des_jantes': {'name': 'dimension des jantes', 'group': 'Equipements divers'},
        'non_fumeur': {'name': 'non fumeur', 'group': 'Equipements divers'},
        'pack_chrome': {'name': 'pack chrome', 'group': 'Equipements divers'},
        'pack_confort': {'name': 'pack confort', 'group': 'Equipements divers'},
        'pack_cuir': {'name': 'pack cuir', 'group': 'Equipements divers'},
        'pack_electrique': {'name': 'pack électrique', 'group': 'Equipements divers'},
        'pack_hifi': {'name': 'pack hifi', 'group': 'Equipements divers'},
        'pack_hiver': {'name': 'pack hiver', 'group': 'Equipements divers'},
        'pack_loisir': {'name': 'pack loisir', 'group': 'Equipements divers'},
        'pack_luxe': {'name': 'pack luxe', 'group': 'Equipements divers'},
        'pack_sport': {'name': 'pack sport', 'group': 'Equipements divers'},
        'pack_visibilite': {'name': "inclus généralement l'allumage automatique des feux et essuie-glaces",
                            'group': 'Equipements divers'},
        'pare_carters': {'name': 'pare carters', 'group': 'Equipements divers'},
        'pare_cylindres': {'name': 'pare cylindres', 'group': 'Equipements divers'},
        'pare_brise_chauffant': {'name': 'pare-brise chauffant', 'group': 'Equipements divers'},
        'pare_buffle': {'name': 'pare-buffle', 'group': 'Equipements divers'},
        'passage_de_roue': {'name': 'passage de roue', 'group': 'Equipements divers'},
        'peinture_integrale': {'name': 'peinture intégrale', 'group': 'Equipements divers'},
        'peinture_personnalisee': {'name': 'peinture personnalisée', 'group': 'Equipements divers'},
        'regulateur_de_vitesse': {'name': 'régulateur de vitesse', 'group': 'Equipements divers'},
        'roues_motrices': {'name': 'roues motrices', 'group': 'Equipements divers'},
        'sabot': {'name': 'sabot', 'group': 'Equipements divers'},
        'sac_reservoir': {'name': 'sac réservoir', 'group': 'Equipements divers'},
        'tuning': {'name': 'tuning', 'group': 'Equipements divers'},
        'attache_remorque': {'name': 'attache remorque', 'group': 'Equipements divers'},
        'tapis_reservoir': {'name': 'tapis de réservoir', 'group': 'Equipements divers'},
        'bas_de_carenage': {'name': 'bas de carénage', 'group': 'Equipements divers'},
        'bequet_central': {'name': 'béquet central', 'group': 'Equipements divers'},
        'support_de_u': {'name': 'support de U', 'group': 'Equipements divers'},
        'clignotants_blancs': {'name': 'clignotants blancs', 'group': 'Equipements divers'},
        'pare_brise': {'name': 'pare-brise', 'group': 'Equipements divers'},
        'echappement_4_1': {'name': 'échappement 4 en 1', 'group': 'Equipements divers'},
        'kit_34ch': {'name': 'kit 34 chevaux', 'group': 'Equipements divers'},
        'silencieux': {'name': 'silencieux', 'group': 'Equipements divers'},
        'support_top_case': {'name': 'support de top case', 'group': 'Equipements divers'},
        'support_valise': {'name': 'support de valise', 'group': 'Equipements divers'},
        'systeme_traqueur': {'name': 'système traqueur', 'group': 'Equipements divers'},
        'top_case_dossier': {'name': 'top case avec dossier passager', 'group': 'Equipements divers'},
        'telephone_bluetooth': {'name': 'appareil pouvant recevoir une carte sim et communiquant via bluetooth',
                                'group': 'Equipements divers'},
        'garde_boue_avant': {'name': 'garde boue avant', 'group': 'Equipements divers'},
        'pot_echappement_sport': {'name': "pot d'échappement sport", 'group': 'Equipements divers'},
        'durites_aviation': {'name': 'fléxibles hydrauliques renforcés', 'group': 'Equipements divers'},
        'selection_titane': {'name': 'sélection titane', 'group': 'Equipements divers'},
        'leche_roue': {'name': 'lèche-roue', 'group': 'Equipements divers'},
        'suspension_renforcee': {'name': 'suspension renforcée', 'group': 'Equipements divers'},
        'limiteur_de_vitesse': {'name': 'limiteur de vitesse', 'group': 'Equipements divers'},
        'filtre_a_particules': {'name': 'filtre à particules', 'group': 'Equipements divers'},
        'phares_a_led': {'name': 'phares à LED', 'group': 'Equipements divers'}, 'stop_start': {
            'name': "dispositif d'arrêt et de redémarrage automatique d'un moteur automobile destiné a économiser le carburant et réduire la pollution",
            'group': 'Equipements divers'}, 'pack_fumeur': {'name': 'Pack fumeur', 'group': 'Equipements divers'},
        'volant_cuir': {'name': 'volant cuir', 'group': 'Equipements divers'},
        'prise_12v': {'name': 'prise 12V', 'group': 'Equipements divers'},
        'support_gps': {'name': 'support universel pour GPS', 'group': 'Equipements divers'},
        'verrouillage_a_distance': {
            'name': 'verrouillage des ouvrants à distance depuis une télécommande généralement sur la clé/carte de démarrage du véhicule',
            'group': 'Equipements divers'},
        'predisposition_attelage': {'name': "véhicule pré-équipé en faisceaux et/ou boîtier pour pose d'attelage",
                                    'group': 'Equipements divers'}, 'palettes_volant': {
            'name': 'Indique la présence de palettes (manette) de changement de vitesse pour boite sequentielle ou auto',
            'group': 'Equipements divers'},
        'preequipement_ipod': {'name': 'Dock connector iPod pour integration avec le changeur CD',
                               'group': 'Equipements divers'},
        'commandes_vocales': {'name': "présence d'un système de contrôle vocale (auto-radio, navigation ou autre)",
                              'group': 'Equipements divers'},
        'cle_mains_libres': {'name': 'dispositif de déverrouillage et/ou démarrage les mains libres (sans clé)',
                             'group': 'Equipements divers'},
        'demarrage_sans_cle': {'name': 'système de démarrage sans clé (généralement par impulsion sur un bouton)',
                               'group': 'Equipements divers'},
        'capot_de_selle': {'name': "présence d'un capot de selle", 'group': 'Equipements divers'},
        'ecopes_de_radiateur': {'name': 'ecopes de radiateur', 'group': 'Equipements divers'},
        'protege_te_de_fourche': {'name': 'protection té de fourche', 'group': 'Equipements divers'},
        'intercom_pilote_passager': {'name': "systeme d'intercommunication pilote/passager",
                                     'group': 'Equipements divers'},
        'support_plaque_mineralogique': {'name': 'support pour plaque minéralogique', 'group': 'Equipements divers'},
        'treuil': {'name': 'Possede treuil', 'group': 'Equipements divers'},
        'protection_de_reservoir': {'name': 'protection de reservoir', 'group': 'Equipements divers'},
        'cache_courroie': {'name': 'cache courroie', 'group': 'Equipements divers'},
        'ouverture_coffre_a_distance': {'name': 'Ouverture du coffre à distance', 'group': 'Equipements divers'},
        'laves_phares_avants': {'name': 'Système de nettoyage des phares avant', 'group': 'Equipements divers'},
        'cache_bagages': {'name': 'Système permettant de cacher le contenu du coffre', 'group': 'Equipements divers'},
        'sieges_arrieres_rabattable': {'name': 'Sieges arrières rabattable', 'group': 'Equipements divers'}
    }

    value = transformation['value']
    equipments = []

    vehicle = value.find('vehicule')
    if vehicle is None:
        return equipments

    for xml_elem in list(vehicle):
        if xml_elem.tag in equipment_list:
            original = xml_elem.tag

            equipments.append({
                'name': equipment_list[xml_elem.tag]['name'],
                'original': original,
                'value': xml_elem.text,
                'group': equipment_list[xml_elem.tag]['group']
            })

    return equipments
